lint:
  files_exist:
    - .github/workflows/branch.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
    - .travis.yml
    - docs/usage.md
    - docs/output.md
    - docs/images/nf-core-autometa_logo.png

  files_unchanged:
    - manifest
    - .github/CONTRIBUTING.md
    - .github/ISSUE_TEMPLATE/bug_report.md
    - .github/ISSUE_TEMPLATE/feature_request.md
    - .github/workflows/linting_comment.yml
    - .github/workflows/linting.yml
    - assets/email_template.html
    - assets/email_template.txt
    - bin/scrape_software_versions.py
    - docs/README.md
    - .gitignore
    - LICENSE
    - .github/PULL_REQUEST_TEMPLATE.md
    - lib/NfcoreTemplate.groovy
  template_strings: false
  nextflow_config: false
