lint:
  files_exist:
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/ISSUE_TEMPLATE/feature_request.yml
    - .github/workflows/branch.yml
    - .github/workflows/ci.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
    - assets/nf-core-autometa_logo_light.png
    - docs/usage.md
    - docs/output.md
    - docs/images/nf-core-autometa_logo.png
    - docs/images/nf-core-autometa_logo_light.png
    - docs/images/nf-core-autometa_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.md
    - .github/ISSUE_TEMPLATE/feature_request.md

  files_unchanged:
    - manifest
    - .github/CONTRIBUTING.md
    - .github/ISSUE_TEMPLATE/bug_report.md
    - .github/ISSUE_TEMPLATE/feature_request.md
    - .github/workflows/linting_comment.yml
    - .github/workflows/linting.yml
    - assets/email_template.html
    - assets/email_template.txt
    - bin/scrape_software_versions.py
    - docs/README.md
    - .gitignore
    - LICENSE
    - .github/PULL_REQUEST_TEMPLATE.md
    - lib/NfcoreTemplate.groovy

  actions_ci:
    - .github/workflows/ci.yml

  schema_lint: true
  template_strings: false
  nextflow_config:
    - manifest.name
    - manifest.homePage
repository_type: pipeline
