name: autometa
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bedtools
  - biopython
  - bowtie2
  - diamond
  - hdbscan
  - hmmer
  - ndcctools
  - numba
  - parallel
  - prodigal
  - requests
  - samtools
  - scikit-learn
  - tqdm
  - umap-learn
