{% set name = "Autometa" %}
{% set data = load_setup_py_data() %}

package:
  name: {{ name|lower }}
  version: {{ data.get('version') }}

source:
  path: ./
  # git_url: https://github.com/WiscEvan/Autometa.git
  # git_rev: 2.0.0-cbld
  # git_depth: 1

build:
  noarch: python
  script: python -m pip install . --ignore-installed --no-deps -vv

requirements:
  host:
    - python >=3
    - pip
    - setuptools
  run:
    - python >=3
    - biopython
    - bedtools
    - bowtie2
    - diamond
    - hmmer
    - hdbscan
    - ndcctools
    - numpy >=1.18.*
    - pandas >=1.*
    - parallel
    - prodigal
    - requests
    - scikit-learn
    - scipy
    - samtools
    - tqdm
    - umap-learn

test:
  imports:
    - autometa
  commands:
    - autometa -h
    - autometa-configure -h
    - autometa-kmers -h
    - autometa-coverage -h
    - autometa-markers -h

about:
  home: https://github.com/WiscEvan/Autometa
  license: GPL3
  license_file: LICENSE.txt
  summary: "Autometa is an automated pipeline to extract genomes from metagenomes."

extra:
  maintainers:
   - Jason C. Kwan
   - Evan R. Rees
