{% set name = "Autometa" %}
{% set data = load_setup_py_data() %}

package:
  name: {{ name|lower }}
  version: {{ data.get('version') }}

source:
  path: ./
  # git_url: https://github.com/KwanLab/Autometa.git
  # git_rev: {{ data.get('version') }}

build:
  noarch: python
  script: python -m pip install . --ignore-installed --no-deps -vv

requirements:
  host:
    - python {{ data.get('python_requires') }}
    - pip
    - setuptools
  run:
    - python {{ data.get('python_requires') }}
    - biopython
    - bedtools
    - bowtie2
    - diamond
    - hmmer
    - hdbscan
    - ndcctools
    - numpy >=1.18.*
    - pandas >=1.*
    - parallel
    - prodigal
    - requests
    - scikit-learn
    - scipy
    - samtools
    - tqdm
    - umap-learn

test:
  imports:
    - autometa
  commands:
    - autometa -h
    - autometa-configure -h
    - autometa-kmers -h
    - autometa-coverage -h
    - autometa-markers -h

about:
  home: {{ data.get('url') }}
  license: AGPL
  license_file: LICENSE.txt
  description: |
    An automated binning pipeline for metagenomes, in particular host-associated and highly complex ones.
    Miller, I. J.; Rees, E. R.; Ross, J.; Miller, I.; Baxa, J.; Lopera, J.; Kerby, R. L.; Rey, F. E.; Kwan, J. C. Autometa: Automated extraction of microbial genomes from individual shotgun metagenomes. Nucleic Acids Research, 2019. DOI: https://doi.org/10.1093/nar/gkz148
  summary: "Autometa: Automated extraction of genomes from shotgun metagenomes."
  doc_url: https://autometa.readthedocs.io/en/latest/
  dev_url: {{ data.get('url') }}

extra:
  maintainers:
   - Jason C. Kwan
   - Evan R. Rees
