{% set name = "Autometa" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/WiscEvan/Autometa.git
  git_rev: 2.0.0-cbld
  git_depth: 1

build:
  numpy: 1.18
  number: 0

requirements:
  host:
    - python
    - numpy 1.18
  run:
    - python
    - biopython
    - pandas
    - tqdm
    - numpy 1.18
    - scikit-learn
    - scipy
    - samtools
    - bedtools
    - bowtie2
    - hmmer
    - pandas
    - prodigal
    - diamond
    - ndcctools
    - parallel
    - requests
    - umap-learn

test:
  imports:
    - autometa

about:
  home: https://github.com/WiscEvan/Autometa
  license: GPL3
