contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #autometa channel"
    url: https://nfcore.slack.com/channels/autometa
    about: Discussion about the nf-core/autometa pipeline
