# Generated by Django 3.0.2 on 2020-02-06 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('startpage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='parameters',
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=127),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='startpage.Project'),
        ),
    ]
