# Derived from https://github.com/jdblischak/smk-simple-slurm
cluster:
  mkdir -p logs/`date +"%d-%m-%y"`/{rule} &&
  sbatch
    --partition={resources.partition}
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --job-name=smk-{rule}-{wildcards}
    --output=logs/`date +"%d-%m-%y"`/{rule}/{rule}-{wildcards}-%j.out
    --parsable
default-resources:
  - partition=queue
  - mem_mb=300000
  - disk_mb=100000
max-jobs-per-second: 10
max-status-checks-per-second: 1
jobs: 50
keep-going: True
rerun-incomplete: True
printshellcmds: True
use-conda: True
cluster-cancel: scancel
