name: autometa

channels:
  - conda-forge
  - bioconda
  - anaconda

dependencies:
  - python==3.7
  - pip
  - pip:
      - sphinxcontrib-programoutput
      - sphinx-rtd-theme
      - Sphinx==2.2.1
      
