name: docker CI/CD

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  docker_build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Autometa Build and push
        id: autometa_docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: jasonkwan/autometa:${{ steps.extract_branch.outputs.branch }}
      - name: Autometa nextflow module docker build and push
        id: nextflow_get_genomes_for_mock_module_docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/modules/get_genomes_for_mock.Dockerfile
          push: true
          tags: jasonkwan/autometa-nf-modules-get_genomes_for_mock:${{ steps.extract_branch.outputs.branch }}
      - name: Autometa nextflow module mock_data_reporter docker build and push
        id: nextflow_mock_data_reporter_module_docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/modules/mock_data_reporter.Dockerfile
          push: true
          tags: jasonkwan/autometa-nf-modules-mock_data_reporter:${{ steps.extract_branch.outputs.branch }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
