name: docker get genomes for mock CI/CD

on:
  push:
    paths-ignore:
        - "docs/**"
    branches:
      - main
      - dev
  pull_request:
    paths-ignore:
      - "docs/**"
    branches:
      - main
      - dev

jobs:
  docker_get_genomes_for_mock:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: jasonkwan/autometa-nf-modules-get_genomes_for_mock
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Autometa nextflow module get_genomes_for_mock docker build and push
        id: nextflow_get_genomes_for_mock_module_docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/modules/get_genomes_for_mock.Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
