name: pytest/codecov

on:
  push:
    # Only perform codecov if autometa or tests have changed...
    paths:
      - "autometa/**"
      - "tests/**"
      - "pytest.ini"
    branches:
      - main
      - dev
  pull_request:
    # Only perform codecov if autometa or tests have changed...
    paths:
      - "autometa/**"
      - "tests/**"
      - "pytest.ini"
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7]
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}
    name: pytest & codecov
    steps:
      - uses: actions/checkout@v2
      - name: Cache conda
        uses: actions/cache@v2
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-py${{ matrix.python-version }}-${{
            hashFiles('tests/environment.yml') }}
      - name: Setup mamba
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          mamba-version: "*"
          channels: conda-forge,bioconda,defaults
          channel-priority: true
          activate-environment: autometa
          environment-file: tests/environment.yml
      - name: Conda config info
        shell: bash -l {0}
        run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show
          printenv | sort
      - name: Download test data
        shell: bash -l {0}
        run: gdown https://drive.google.com/uc\?\id=1bSlPldaq3C6Cf9Y5Rm7iwtUDcjxAaeEk -O tests/data/test_data.json
      - name: Run pytest
        shell: bash -l {0}
        run: python -m pytest --cov-report=xml --cov=autometa tests/
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          env_vars: OS,PYTHON
          flags: unittests
          verbose: true
